[build]
  command = "bundle exec jekyll build"
  publish = "_site/"

[build.environment]
  RUBY_VERSION = "3.0.0"
  BUNDLER_VERSION = "2.5.6"

[[plugins]]
  package = "@netlify/plugin-cache"

[[plugins]]
  package = "@netlify/plugin-ruby"
